# This is a basic workflow to help you get started with Actions

name: auto

# Controls when the workflow will run
on:
  # 在推送到 master 分支时会自动运行一次
  # push:
  #   branches: 
  #     - main
  # 可以设定定时任务执行
  schedule:
    # UTC 22 点 34 定期执行一次，跟北京时间大概相距8小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间 5 点 34 以后
    - cron: '13 6 * * *'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  auto_sign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 将本仓库的代码拉取一份到虚拟环境机器上
      - name: Checkout
        uses: actions/checkout@v2
      # 配置安装 python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # 配置安装依赖包
      - name: Install requirements
        run: pip install -r requirements.txt
      # 验证secrets配置
      - name: Check secrets
        run: |
          echo "准备运行脚本"
          echo "COOKIE is set: ${{ secrets.COOKIE != '' }}"
          echo "SK is set: ${{ secrets.SK != '' }}"
          echo "TOKEN is set: ${{ secrets.TOKEN != '' }}"
      # 运行 python 脚本文件，其中的参数取 secrets 中配置的加密参数，账户名和密码
      - name: Working
        run: |
          random_time=$(($RANDOM % 16))
          echo "等待 ${random_time} 分钟后开始签到"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          python auto_signV2.py 
